// This file is automatically generated. Do not modify.
package dev.turtywurty.pepolang.parser;

import dev.turtywurty.pepolang.JavaGenerated;
import dev.turtywurty.pepolang.lexer.Token;
import java.util.List;

@JavaGenerated
public abstract class Expression {
    public abstract <R> R accept(ExpressionVisitor<R> visitor);

    public static class Assign extends Expression {
        private final Token name;

        private final Expression value;

        public Assign(Token name, Expression value) {
            this.name = name;
            this.value = value;
        }

        @Override
        public <R> R accept(ExpressionVisitor<R> visitor) {
            return visitor.visitAssign(this);
        }

        public Token getName() {
            return this.name;
        }

        public Expression getValue() {
            return this.value;
        }
    }

    public static class Binary extends Expression {
        private final Expression left;

        private final Token operator;

        private final Expression right;

        public Binary(Expression left, Token operator, Expression right) {
            this.left = left;
            this.operator = operator;
            this.right = right;
        }

        @Override
        public <R> R accept(ExpressionVisitor<R> visitor) {
            return visitor.visitBinary(this);
        }

        public Expression getLeft() {
            return this.left;
        }

        public Token getOperator() {
            return this.operator;
        }

        public Expression getRight() {
            return this.right;
        }
    }

    public static class Call extends Expression {
        private final Expression callee;

        private final Token paren;

        private final List<Expression> arguments;

        public Call(Expression callee, Token paren, List<Expression> arguments) {
            this.callee = callee;
            this.paren = paren;
            this.arguments = arguments;
        }

        @Override
        public <R> R accept(ExpressionVisitor<R> visitor) {
            return visitor.visitCall(this);
        }

        public Expression getCallee() {
            return this.callee;
        }

        public Token getParen() {
            return this.paren;
        }

        public List<Expression> getArguments() {
            return this.arguments;
        }
    }

    public static class New extends Expression {
        private final Token keyword;

        private final Expression call;

        public New(Token keyword, Expression call) {
            this.keyword = keyword;
            this.call = call;
        }

        @Override
        public <R> R accept(ExpressionVisitor<R> visitor) {
            return visitor.visitNew(this);
        }

        public Token getKeyword() {
            return this.keyword;
        }

        public Expression getCall() {
            return this.call;
        }
    }

    public static class Get extends Expression {
        private final Expression object;

        private final Token name;

        public Get(Expression object, Token name) {
            this.object = object;
            this.name = name;
        }

        @Override
        public <R> R accept(ExpressionVisitor<R> visitor) {
            return visitor.visitGet(this);
        }

        public Expression getObject() {
            return this.object;
        }

        public Token getName() {
            return this.name;
        }
    }

    public static class Set extends Expression {
        private final Expression object;

        private final Token name;

        private final Expression value;

        public Set(Expression object, Token name, Expression value) {
            this.object = object;
            this.name = name;
            this.value = value;
        }

        @Override
        public <R> R accept(ExpressionVisitor<R> visitor) {
            return visitor.visitSet(this);
        }

        public Expression getObject() {
            return this.object;
        }

        public Token getName() {
            return this.name;
        }

        public Expression getValue() {
            return this.value;
        }
    }

    public static class This extends Expression {
        private final Token keyword;

        public This(Token keyword) {
            this.keyword = keyword;
        }

        @Override
        public <R> R accept(ExpressionVisitor<R> visitor) {
            return visitor.visitThis(this);
        }

        public Token getKeyword() {
            return this.keyword;
        }
    }

    public static class Super extends Expression {
        private final Token keyword;

        private final Token method;

        public Super(Token keyword, Token method) {
            this.keyword = keyword;
            this.method = method;
        }

        @Override
        public <R> R accept(ExpressionVisitor<R> visitor) {
            return visitor.visitSuper(this);
        }

        public Token getKeyword() {
            return this.keyword;
        }

        public Token getMethod() {
            return this.method;
        }
    }

    public static class Grouping extends Expression {
        private final Expression expression;

        public Grouping(Expression expression) {
            this.expression = expression;
        }

        @Override
        public <R> R accept(ExpressionVisitor<R> visitor) {
            return visitor.visitGrouping(this);
        }

        public Expression getExpression() {
            return this.expression;
        }
    }

    public static class Literal extends Expression {
        private final Object value;

        public Literal(Object value) {
            this.value = value;
        }

        @Override
        public <R> R accept(ExpressionVisitor<R> visitor) {
            return visitor.visitLiteral(this);
        }

        public Object getValue() {
            return this.value;
        }
    }

    public static class Logical extends Expression {
        private final Expression left;

        private final Token operator;

        private final Expression right;

        public Logical(Expression left, Token operator, Expression right) {
            this.left = left;
            this.operator = operator;
            this.right = right;
        }

        @Override
        public <R> R accept(ExpressionVisitor<R> visitor) {
            return visitor.visitLogical(this);
        }

        public Expression getLeft() {
            return this.left;
        }

        public Token getOperator() {
            return this.operator;
        }

        public Expression getRight() {
            return this.right;
        }
    }

    public static class Unary extends Expression {
        private final Token operator;

        private final Expression right;

        public Unary(Token operator, Expression right) {
            this.operator = operator;
            this.right = right;
        }

        @Override
        public <R> R accept(ExpressionVisitor<R> visitor) {
            return visitor.visitUnary(this);
        }

        public Token getOperator() {
            return this.operator;
        }

        public Expression getRight() {
            return this.right;
        }
    }

    public static class Variable extends Expression {
        private final Token name;

        public Variable(Token name) {
            this.name = name;
        }

        @Override
        public <R> R accept(ExpressionVisitor<R> visitor) {
            return visitor.visitVariable(this);
        }

        public Token getName() {
            return this.name;
        }
    }

    public static class Function extends Expression {
        private final Token name;

        public Function(Token name) {
            this.name = name;
        }

        @Override
        public <R> R accept(ExpressionVisitor<R> visitor) {
            return visitor.visitFunction(this);
        }

        public Token getName() {
            return this.name;
        }
    }

    public static class Extends extends Expression {
        private final Token name;

        public Extends(Token name) {
            this.name = name;
        }

        @Override
        public <R> R accept(ExpressionVisitor<R> visitor) {
            return visitor.visitExtends(this);
        }

        public Token getName() {
            return this.name;
        }
    }
}
