// This file is automatically generated. Do not modify.
package dev.turtywurty.pepolang.parser;

import dev.turtywurty.pepolang.JavaGenerated;
import dev.turtywurty.pepolang.lexer.Token;

@JavaGenerated
public abstract class Statement {
    public abstract <R> R accept(StatementVisitor<R> visitor);

    public static class ExpressionStatement extends Statement {
        private final Expression expression;

        public ExpressionStatement(Expression expression) {
            this.expression = expression;
        }

        @Override
        public <R> R accept(StatementVisitor<R> visitor) {
            return visitor.visitExpressionStatement(this);
        }

        public Expression getExpression() {
            return this.expression;
        }
    }

    public static class PrintStatement extends Statement {
        private final Expression expression;

        public PrintStatement(Expression expression) {
            this.expression = expression;
        }

        @Override
        public <R> R accept(StatementVisitor<R> visitor) {
            return visitor.visitPrintStatement(this);
        }

        public Expression getExpression() {
            return this.expression;
        }
    }

    public static class VariableStatement extends Statement {
        private final Expression initializer;

        private final Token name;

        private final Token type;

        public VariableStatement(Expression initializer, Token name, Token type) {
            this.initializer = initializer;
            this.name = name;
            this.type = type;
        }

        @Override
        public <R> R accept(StatementVisitor<R> visitor) {
            return visitor.visitVariableStatement(this);
        }

        public Expression getInitializer() {
            return this.initializer;
        }

        public Token getName() {
            return this.name;
        }

        public Token getType() {
            return this.type;
        }
    }
}
