// This file is automatically generated. Do not modify.
package dev.turtywurty.pepolang.parser;

import dev.turtywurty.pepolang.parser.Expression.Binary;
import dev.turtywurty.pepolang.parser.Expression.Grouping;
import dev.turtywurty.pepolang.parser.Expression.Literal;
import dev.turtywurty.pepolang.parser.Expression.Unary;
import dev.turtywurty.pepolang.tooling.JavaGenerated;

@JavaGenerated
public interface Visitor<R> {
    R visitBinary(Binary expression);

    R visitGrouping(Grouping expression);

    R visitLiteral(Literal expression);

    R visitUnary(Unary expression);
}
